services:
  - type: web
    name: school-admission-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_APP
        value: main.py
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
