"""Fix foreign key relationships

Revision ID: fea9f408530c
Revises: ea4786cd1c82
Create Date: 2025-05-13 19:03:51.815457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fea9f408530c'
down_revision = 'ea4786cd1c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('estudent')
    with op.batch_alter_table('e_students', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('e_students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('estudent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('roll_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name='estudent_class_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='estudent_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='estudent_pkey'),
    sa.UniqueConstraint('roll_number', name='estudent_roll_number_key'),
    sa.UniqueConstraint('student_id', name='estudent_student_id_key')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('father_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('mother_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('student_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('village', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('previous_school', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_admitted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('admission_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('follow_up_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='student_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_pkey')
    )
    # ### end Alembic commands ###
